[phases.setup]
nixPkgs = ['nodejs_22', 'bun']

[phases.install]
cmds = [
    'cd ../.. && bun install --frozen-lockfile',
    'cd ../.. && bun run build --filter=@tasker/openapi --filter=@tasker/zod'
]

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bun run preview -- --port ${PORT:-3000} --host 0.0.0.0'

[variables]
NODE_ENV = 'production'